
'use server';

import { collection, addDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import type { Recipe } from '@/lib/types';
import type { DishConceptOutput } from '@/ai/flows/workshop-flow';

/**
 * Creates a new dish (recipe of type 'Plat') from a concept generated by the workshop AI.
 * It stores the suggested ingredients in a temporary field for later processing on the client.
 * @param concept - The dish concept generated by the AI.
 * @returns The ID of the newly created dish.
 */
export async function createDishFromWorkshop(concept: DishConceptOutput): Promise<string> {
    try {
        const dishData: Omit<Recipe, 'id' | 'suggestedIngredients'> = {
            type: 'Plat',
            name: concept.name,
            description: concept.description,
            imageUrl: concept.imageUrl,
            procedure_preparation: concept.procedure_preparation,
            procedure_cuisson: concept.procedure_cuisson,
            procedure_service: concept.procedure_service,
            difficulty: concept.difficulty,
            duration: concept.duration,
            portions: concept.portions,
            commercialArgument: concept.commercialArgument,
            price: 0, 
            status: 'Inactif',
            category: 'Plats et Grillades',
            tvaRate: 10,
        };

        const recipesCol = collection(db, 'recipes');
        const recipeDocRef = await addDoc(recipesCol, dishData);
        
        return recipeDocRef.id;

    } catch (error) {
        console.error("Error creating dish from workshop:", error);
        if (error instanceof Error) {
            throw new Error(`Failed to create dish: ${error.message}`);
        }
        throw new Error("An unknown error occurred while creating the dish from the workshop concept.");
    }
}
